name: Find Terraform Modules
description: Returns the directories for perceived Terraform modules
inputs:
  patterns:
    description: Comma separated list patterns to search for
    default: '**/*.tf?(.json)'
outputs:
  directories:
    description: Terraform module directories
runs:
  using: node12
  main: dist/index.js
